USE [CrimeDW]
GO

CREATE TABLE [CrimeDW].[DimCity](
	[CityID] [int] IDENTITY(1,1) NOT NULL,
	[City] [varchar](100) NULL,
	[StateID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [Crime].[DimCity]  WITH CHECK ADD  CONSTRAINT [FK_StateID] FOREIGN KEY([StateID])
REFERENCES [Crime].[DimState] ([StateID])
GO

ALTER TABLE [Crime].[DimCity] CHECK CONSTRAINT [FK_StateID]
GO


